# Use the pre-built Kilosort2 base image from spikeinterface
#FROM spikeinterface/kilosort2-compiled-base
FROM rohanmalige/benshalom:v3

# # Install system dependencies
# RUN apt-get update && \
#     apt-get install -y \
#     wget \
#     unzip \
#     ca-certificates \
#     libffi-dev \
#     libgcc-9-dev \
#     libgomp1 \
#     libstdc++-9-dev \
#     ncurses-dev \
#     libssl-dev \
#     libsqlite3-dev \
#     tk-dev \
#     zlib1g-dev \
#     software-properties-common \
#     && rm -rf /var/lib/apt/lists/*

# # Add deadsnakes PPA and install Python 3.8 and pip
# RUN add-apt-repository ppa:deadsnakes/ppa && \
#     apt-get update && \
#     apt-get install -y python3.8 python3.8-distutils && \
#     wget https://bootstrap.pypa.io/get-pip.py && \
#     python3.8 get-pip.py && \
#     ln -s /usr/bin/python3.8 /usr/bin/python && \
#     ln -s /usr/local/bin/pip /usr/bin/pip && \
#     rm get-pip.py

# Upgrade pip and setuptools
RUN pip install --upgrade pip setuptools

# Install Python packages
RUN pip install \
    asciitree==0.3.3 \
    asttokens==2.4.1 \
    attrs==24.2.0 \
    backcall==0.2.0 \
    beautifulsoup4==4.12.3 \
    bleach==6.1.0 \
    certifi==2024.8.30 \
    charset-normalizer==3.4.0 \
    contourpy==1.1.1 \
    cuda-python==12.3.0 \
    cycler==0.12.1 \
    cython==3.0.11 \
    decorator==5.1.1 \
    defusedxml==0.7.1 \
    dill==0.3.9 \
    distinctipy==1.3.4 \
    docker==7.1.0 \
    docopt==0.6.2 \
    executing==2.1.0 \
    fasteners==0.19 \
    fastjsonschema==2.20.0 \
    find-libpython==0.4.0 \
    fonttools==4.54.1 \
    h5py==3.11.0 \
    idna==3.10 \
    importlib-metadata==8.5.0 \
    importlib-resources==6.4.5 \
    ipython==8.12.3 \
    jedi==0.19.1 \
    jinja2==3.1.4 \
    joblib==1.4.2 \
    jsonschema==4.23.0 \
    jsonschema-specifications==2023.12.1 \
    jupyter-client==8.6.3 \
    jupyter-core==5.7.2 \
    jupyterlab-pygments==0.3.0 \
    kiwisolver==1.4.7 \
    lfpy==2.3.2 \
    lfpykit==0.5.1 \
    llvmlite==0.41.1 \
    markupsafe==2.1.5 \
    matplotlib==3.7.5 \
    matplotlib-inline==0.1.7 \
    meautility==1.5.1 \
    mistune==3.0.2 \
    nbclient==0.10.0 \
    nbconvert==7.16.4 \
    nbformat==5.10.4 \
    neo==0.13.3 \
    networkx==3.1 \
    neuron==8.2.6 \
    numba==0.58.1 \
    numcodecs==0.12.1 \
    numpy==1.24.4 \
    packaging==24.1 \
    pandas==2.0.3 \
    pandas-flavor==0.6.0 \
    pandocfilters==1.5.1 \
    parso==0.8.4 \
    patsy==0.5.6 \
    pexpect==4.9.0 \
    pickleshare==0.7.5 \
    pillow==10.4.0 \
    pingouin==0.5.5 \
    pipreqs==0.5.0 \
    pkgutil-resolve-name==1.3.10 \
    platformdirs==4.3.6 \
    probeinterface==0.2.24 \
    prompt-toolkit==3.0.48 \
    ptyprocess==0.7.0 \
    pure-eval==0.2.3 \
    pygments==2.18.0 \
    pyparsing==3.1.4 \
    python-dateutil==2.9.0.post0 \
    pytz==2024.2 \
    pyyaml==6.0.2 \
    pyzmq==26.2.0 \
    quantities==0.15.0 \
    referencing==0.35.1 \
    requests==2.32.3 \
    rpds-py==0.20.1 \
    scikit-learn==1.3.2 \
    scipy==1.10.1 \
    seaborn==0.13.2 \
    six==1.16.0 \
    soupsieve==2.6 \
    spikeinterface==0.100.4 \
    stack-data==0.6.3 \
    statsmodels==0.14.1 \
    tabulate==0.9.0 \
    threadpoolctl==3.5.0 \
    tinycss2==1.4.0 \
    tornado==6.4.1 \
    tqdm==4.66.6 \
    traitlets==5.14.3 \
    typing-extensions==4.12.2 \
    tzdata==2024.2 \
    urllib3==2.2.3 \
    wcwidth==0.2.13 \
    webencodings==0.5.1 \
    xarray==2023.1.0 \
    yarg==0.1.9 \
    zarr==2.16.1 \
    zipp==3.20.2

# Copy the Maxwell HDF5 plugin to the container (adjust the path as needed)
COPY maxwell_hdf5_plugin /opt/maxwell_hdf5_plugin

# Set the HDF5_PLUGIN_PATH environment variable
ENV HDF5_PLUGIN_PATH=/opt/maxwell_hdf5_plugin/Linux

# Set the working directory (uncomment and adjust as needed)
# WORKDIR /workspace/RBS_axonal_reconstructions

# Default command to provide an interactive shell
#CMD ["bash"]


# # Use the pre-built Kilosort2 base image from spikeinterface
# FROM spikeinterface/kilosort2-compiled-base

# # Copy the environment file to the container
# COPY axon_env.yml /tmp/axon_env.yml

# # Install the custom conda environment
# RUN conda env create -f /tmp/axon_env.yml

# # Set the environment path to prioritize the new conda environment
# #ENV PATH /opt/conda/envs/axon_env/bin:$PATH

# # Ensure that the new environment is always active by default
# RUN echo "source activate axon_env" >> ~/.bashrc

# # Copy the Maxwell HDF5 plugin to the container (adjust the path as needed)
# COPY maxwell_hdf5_plugin /opt/maxwell_hdf5_plugin

# # Set the HDF5_PLUGIN_PATH environment variable
# ENV HDF5_PLUGIN_PATH=/opt/maxwell_hdf5_plugin/Linux

# # Install additional tools, if necessary
# RUN apt-get update && \
#     apt-get install -y wget unzip && \
#     rm -rf /var/lib/apt/lists/*

# # Set the working directory (uncomment and adjust as needed)
# # WORKDIR /workspace/RBS_axonal_reconstructions

# # Initialize the axon_env environment
# RUN /bin/bash -c "source ~/.bashrc && source activate axon_env"

# # Default command to activate the environment and provide an interactive shell
# CMD ["bash", "-c", "source ~/.bashrc && source activate axon_env && exec bash"]