analysis_name: Media_Density_T3_07012025_AR_M07137_multiday
runtime_env_file: /home/adamm/dev/projects/260121_debugging_individual_axon_recon_steps/debug.env
out_dir: /home/adamm/dev/symlinks/local_RBS_data/outputs/Media_Density_T3_07012025_AR/cross_well_analysis_outputs/Media_Density_T3_07012025_AR_M07137_multiday
electrode_pitch_um: 17.5
datasets:
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250708/M07137/Network/000032/data.raw.h5
  DIV: 7
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250708/M07137/Network/000033/data.raw.h5
  DIV: 7
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250710/M07137/Network/000084/data.raw.h5
  DIV: 9
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250710/M07137/Network/000085/data.raw.h5
  DIV: 9
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250714/M07137/Network/000101/data.raw.h5
  DIV: 11
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250714/M07137/Network/000102/data.raw.h5
  DIV: 11
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250717/M07137/Network/000146/data.raw.h5
  DIV: 14
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250717/M07137/Network/000147/data.raw.h5
  DIV: 14
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250721/M07137/Network/000171/data.raw.h5
  DIV: 18
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250721/M07137/Network/000172/data.raw.h5
  DIV: 18
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250728/M07137/Network/000223/data.raw.h5
  DIV: 21
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
- raw_data_h5_path: /home/adamm/dev/symlinks/local_RBS_data/raw_data/Media_Density_T3_07012025_AR/Media_Density_T3_07012025_AR/250728/M07137/Network/000224/data.raw.h5
  DIV: 21
  wells:
  - well_id: well001
    condition: 80K NBP
    plating_density_nbp: 80000
    genotype: WT
  - well_id: well004
    condition: 100K NBP
    plating_density_nbp: 100000
    genotype: WT
  - well_id: well003
    condition: 120K NBP
    plating_density_nbp: 120000
    genotype: WT
