analysis_name: EXAMPLE_multiday_cross_well

runtime_env_file: /abs/path/to/debug.env
out_dir: /abs/path/to/outputs/<dataset>/cross_well_analysis_outputs/<analysis_name>

electrode_pitch_um: 17.5

datasets:
  - raw_data_h5_path: /abs/path/to/raw_data/<dataset>/<dataset>/<YYMMDD>/<mouse>/AxonTracking/<run_id>/data.raw.h5
    DIV: 7
    wells:
      - well_id: well001
        condition: 80K NBP
        plating_density_nbp: 80000
        genotype: WT
      - well_id: well004
        condition: 100K NBP
        plating_density_nbp: 100000
        genotype: WT
      - well_id: well003
        condition: 120K NBP
        plating_density_nbp: 120000
        genotype: WT

  - raw_data_h5_path: /abs/path/to/raw_data/<dataset>/<dataset>/<YYMMDD>/<mouse>/AxonTracking/<run_id>/data.raw.h5
    DIV: 9
    wells:
      - well_id: well001
        condition: 80K NBP
        plating_density_nbp: 80000
        genotype: WT
      - well_id: well004
        condition: 100K NBP
        plating_density_nbp: 100000
        genotype: WT
      - well_id: well003
        condition: 120K NBP
        plating_density_nbp: 120000
        genotype: WT
